modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="mo_potions"
version="1.5-RELEASE+1.19.2MC"
displayName="Mo' Potions"
credits="N/A"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mo-potions"
logoFile="logo.png"
authors="LDM"
description='''
Adds more potions to Minecraft! You can now brew almost anything, from Haste to Blindness!
'''

[[dependencies.mo_potions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




